name: Check module header content
on:
 # pull_request:
   # branches: [ "main" ]
   # types: [opened, synchronize]
#temporarily turned off running on PR so not needlessly running this action over and over again while working on figuring out version
    # for manual running from Actions tab while figuring out
  workflow_dispatch:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script to check all module header field content
        run: bash assets/fields_check_template_specific.sh
