name: ubuntu Check modules in PR for version incrementation
on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 2
      - name: check shell
        run: echo $SHELL
      - name: set default shell to bash instead of dash
        run: sudo dpkg-reconfigure dash
      - name: check shell again
        run: echo $SHELL
      - name: Get git diff to feed to script
        run: |
          git fetch origin main
          git diff origin/main HEAD > git_diff.txt
      - name: check git diff
        run: cat git_diff.txt
      - name: Check version numbers
        run: bash assets/check_versions_ubuntu.sh git_diff.txt