name: Check modules in PR for version incrementation
on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 2
      - name: testing what various refs print as
        run: echo "ref - ${{ github.ref }} ref_name - ${{ github.ref_name }} ref head ${{ GITHUB.HEAD_REF }}" 
      - name: Get git diff to feed to script
        run: git diff origin/main..origin/${{ github.head_ref }} > git_diff.txt
      - name: peek at diff to make sure it looks right
        run: cat git_diff.txt
